### ISSUE TITLE
What are the benefits over similar pure CSS approaches

### ISSUE THREAD

**Issue by fluxxus** [typeplate/typelock#1]
For example, this codepen demo here https://codepen.io/dannievinther/pen/GNExxb

In that demo there is no line-height clamping, but the rest seems very similar.

Also, any tips on how to choose the scale factor? Is it purely random?

**Comment by dennisgaebel** [comment]
There are no benefits. Its just an approach using JavaScript that is more dynamic compared to CSS. Scale factors are personal choice and no right/wrong value for what you desire.
